name: Build

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bionic-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container: 
      image: pllee4/ubuntu-ci:18.04-gRPC
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=/opt/pllee4 .. && cmake --build . 
